### ISSUE TITLE
coc.nvim pyls time out

### ISSUE THREAD

**Issue by esn89** [neoclide/coc-pyls#6]
I keep getting this error message:
![img](https://i.imgur.com/vZT16Sl.png)

I installed via :CocInstall coc-pyls
and made sure pyls is in my path.

The pyls version from pip is:
python-language-server             0.22.0

The build of Coc.nvim I am using is:
 v0.0.50

And I am using neovim: 
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/config -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/src/nvim/auto -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.4/share/nvim"

Run :checkhealth for more info
```

**Comment by chemzqm** [comment]
I got same issue sometimes, it's problem of pyls which I can't help.

**Comment by esn89** [comment]
Ah, seriously?

Is it a matter of time before the server goes up?  
If so, how long do I have to wait?  Right now, I cannot even get any completions showing up.  Is there a known work around?

**Comment by chemzqm** [comment]
>  how long do I have to wait? 

I don't know, maybe 5s. Use MPLS instead, checkout #5

**Comment by esn89** [comment]
Do these DLLs run on mac/linux?

**Comment by chemzqm** [comment]
Yes, they can work.

**Comment by esn89** [comment]
By the way, are you able to use 'rename' in coc.nvim under pyls?

When I try to rename, I get this:

![img](https://i.imgur.com/gGSitpp.png)

Is this a problem of coc or pyls?

**Comment by chemzqm** [comment]
It's bug of pyls, you have to save the buffer before rename, it's badly implemented.
